services:
  db:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    image: wordpress:php8.2-apache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      TZ: ${TZ}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
        define('WP_ENVIRONMENT_TYPE', 'development');
        @ini_set('display_errors', 0);
    volumes:
      # WordPress core + uploads persist in a named volume
      - wp_data:/var/www/html
      # Your plugin live-mounted for instant edits
      - ./woocommerce-variant-modal:/var/www/html/wp-content/plugins/woocommerce-variant-modal:rw,cached

  cli:
    image: wordpress:cli
    depends_on:
      - wordpress
      - db
    user: "33:33" # www-data
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - wp_data:/var/www/html
      - ./woocommerce-variant-modal:/var/www/html/wp-content/plugins/woocommerce-variant-modal

  phpmyadmin:
    image: phpmyadmin:5-apache
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "8080:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  wp_data:
  db_data:

